PACKAGE_NAME="pcieuni"
PACKAGE_VERSION="#MODULE_VERSION#"
CLEAN="make KVERSION=$kernelver clean"
BUILT_MODULE_NAME[0]="pcieuni"
MAKE[0]="make KVERSION=$kernelver"
BUILT_MODULE_LOCATION[0]="./"
DEST_MODULE_LOCATION[0]="/updates"
BUILD_DEPENDS[0]="gpcieuni"
AUTOINSTALL="yes"
